# Imagem Base
FROM osrf/ros:jazzy-desktop-full

# Atualiza os pacotes do Ubuntu e instala o pip
RUN apt update && apt upgrade -y
RUN apt install -y python3-pip

# Comando executado ao iniciar o container
CMD ["/bin/bash"]

